### ISSUE TITLE
Add Support for #return 

### ISSUE THREAD

**Issue by razer1122** [alan-cooney/appsync-template-tester#21]
Hello everyone, 

I just tried out your code and it works splendid. 

However, I came accross some obstacles. Is it planned to add the `#return` command as well? See https://docs.aws.amazon.com/appsync/latest/devguide/resolver-util-reference.html

Also I came across another issue. Somehow the set values don't get resolved correctly if they are not defined and resolved with `$util` functionallity. For example when having the following template  
```
#set($notDefined = $util.escapeJavaScript($notDefined))

#if($util.isNullOrEmpty($notDefined))
{ 
  "this-should-be-outputted": null
}
#else
{
  "this-will-be-outputted": "$notDefined"
}
#end
```

The upper json should be returned then. However, appsync would resolve to the bottom json. 

The response I get in the test is then

```
{
  "this-will-be-outputted": "undefined"
}
```

Thank you very much for your time! 

Best wishes, 
Sebastian

**Comment by razer1122** [comment]
I just tried it out again today. `#return(object)` works. it is just that `#return` without the paranthesis is somehow not recognized. 

so 

```
#return
```

retruns the string "#return" isntead of `null`

**Comment by alan-cooney** [comment]
Thanks for reporting - unfortunately this appears to be a limitation of `velocityjs`
